services:

  postgres:
    image: postgres:18-alpine
    restart: on-failure
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME} -d ${SPRING_DATASOURCE_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: orderservice
    restart: on-failure
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy

    env_file:
      - .env

volumes:
  postgres_data:
